server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/v1/telemetry {
        proxy_pass http://telemetry-service:8082;
        proxy_set_header Host $host;
    }

    location /api/v1/ {
        proxy_pass http://device-service:8083;
        proxy_set_header Host $host;
    }

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;
}
